@startuml
GoodsFront -> ProductPromotionCompose: queryProductPromotionsFromCache
ProductPromotionCompose -> DepositCacheService:multiGetByGoodsIdListWithNotEnd()
ProductPromotionCompose <-  DepositCacheService
ProductPromotionCompose -> ProductPromotionProcessorFactory:getProcessorByTpe()
ProductPromotionCompose <-ProductPromotionProcessorFactory:ProductPromotionProcessor
ProductPromotionCompose ->ProductPromotionProcessor:process
ProductPromotionCompose <-ProductPromotionProcessor
GoodsFront <- ProductPromotionCompose
@enduml